server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: user
#          uri: lb://service-consumer
#          predicates:
#            - Path=/user/**
#          filters:
#            - PreserveHostHeader
#            - StripPrefix=1

        - id: manager
          uri: lb://service-consumer
          predicates:
            - Path=/manager/**
          filters:
            - PreserveHostHeader


        - id: gateway
          uri: lb://service-consumer
          predicates:
            - Path=/**
          filters:
            - PreserveHostHeader

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/